# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Item"
imports_layout = "Vertical"

# Code
use_field_init_shorthand = true

# Comments
format_code_in_doc_comments = true
wrap_comments = true
